### ISSUE TITLE
Add this code to somewhere css

### ISSUE THREAD

**Issue by kamontat** [Database-Systems-For-SKE/Frontend#7]
```css
pre {
        -moz-tab-size: 4; /* Firefox 4+ */
        -o-tab-size: 4; /* Opera 11.5 & 12.1 only */
        tab-size: 4; /* Chrome 21+, Safari 6.1+, Opera 15+ */
}
```
